# ----- NBV CALCULATION -----

maxIterationSteps: 20
epsilon: 0.01 # minimum rating difference of NBVs from 2 consecutive iteration steps. As long as this difference is bigger than epsilon, further iteration steps are executed.
nRatingThreads: -1 # number of rating threads used to rate views. -1 gets an optimal a number of threads, otherwise the {nRatingThreads} threads are used

useMinUtility: true # if true, views are filtered by a minimum required utility. All generated views that are below are removed
enableCropBoxFiltering : false # whether crop box filtering should be used, so that all points of the point_cloud which are at the outside will be removed


# ----- RATING -----

# ratingModuleId == 1 => DefaultRatingModule
ratingModuleId: 1
useTargetRobotState: false # whether it should be checked if the calculated target robot state is reachable

mOmegaUtility: 60 # weighting factor for the usage
mOmegaPan: 1  # weighting factor for rotating the pan-axis of the PTU
mOmegaTilt: 1 # weighting factor for rotating of the tilt-axis of the PTU
mOmegaRot: 10 # weighting factor for rotating the base
mOmegaBase: 135 # weighting factor for moving the base
mOmegaRecognizer: 10 # weighting factor for object detection
speedFactorRecognizer: 3.0 # time costs for object detection in in sec/object

mRatingNormalAngleThreshold: 45.0 # used to rate angles in rating module

# enable / disable parts of utility calculation for testing purposes
useOrientationUtility: true
useProximityUtility: true
useSideUtility: true

enableIntermediateObjectWeighting : false # whether intermediate object weighting should be used for calculating the NextBestView


# ----- CAMERA MODEL FILTER -----

# cameraFilterId == 1 => StereoCameraModelFilter
# cameraFilterId == 2 => SingleCameraModelFilter
cameraFilterId: 1

fovx: 30 # horizontal field of view in degree
fovy: 20 # vertical field of view in degree
ncp: 0.4 # distance of near clipping plane in meters
fcp: 1.5 # distance of far clipping plane in meters

# ----- HYPOTHESIS UPDATER -----

# hypothesisUpdaterId == 1 => PerspectiveHypothesisUpdater
# hypothesisUpdaterId == 2 => DefaultHypothesisUpdater
hypothesisUpdaterId: 1

mHypothesisUpdaterAngleThreshold: 45.0 # used to rate angles in hypothesis updater module


# ----- SPACE SAMPLER -----

# spaceSamplerId == 1 => MapBasedHexagonSpaceSampler
# spaceSamplerId == 2 => MapBasedRandomSpaceSampler
# spaceSamplerId == 3 => PlaneSubSpaceSampler
# spaceSamplerId == 4 => Raytracing2DBasedSpaceSampler
spaceSamplerId: 1

radius: 0.15 # hexagon radius if using the MapBasedHexagonSpaceSampler
sampleSizeMapBasedRandomSpaceSampler: 100 # number of samples if using the MapBasedRandomSpaceSampler


# ----- UNIT SPHERE SAMPLER -----

# sphereSamplerId == 1 => SpiralApproxUnitSphereSampler
sphereSamplerId: 1

sampleSizeUnitSphereSampler: 384 # number of samples created by SpiralApproxUnitSphereSampler. Greater -> more precise orientation.


# ----- MAP -----

colThresh: 40 # greater values results in problems during simulation in navigation. Smaller -> greater distance to obstacles.


# ----- OUTPUT -----

debugLevels: "[NONE]" # ALL, NONE, PARAMETERS, SERVICE_CALLS, VISUALIZATION, CALCULATION, RATING, ROBOT_MODEL, MAP, WORLD, VOXEL_GRID, FILTER, IK_RATING, SPACE_SAMPLER, HYPOTHESIS_UPDATER
