mOmegaUtility: 210 # weighting factor for the usage
mOmegaPan: 1  # weighting factor for rotating the pan-axis of the PTU
mOmegaTilt: 1 # weighting factor for rotating of the tilt-axis of the PTU
mOmegaRot: 10 # weighting factor for rotating the base
mOmegaBase: 250 # weighting factor for moving the base
mOmegaRecognizer: 30
speedFactorRecognizer: 2.0 # time costs for object detection in in sec/object. Please change only after consulting Pascal.
tolerance: 0.00003 # tolerance for pathfinding of global planer
useGlobalPlanner: false
fovx: 30
fovy: 20
ncp: 0.7 # distance to NearClippingPlane in meter
fcp: 1.2 # distance to FarClippingPlane in meter
show_space_sampling: true
show_point_cloud: true
show_frustum_point_cloud: true
show_frustum_marker_array: true
visualizeIK: false
IKAngleRating: ANGLE_APPROXIMATION #The rating algorithm used for the orientation angle sampling in the MILDRobotModelWithExactIK module. Available algorithms are: ANGLE_APPROXIMATION, NAVIGATION_PATH, SIMPLE
# cameraFilterId == 1 => Raytracing3DBasedStereoCameraModelFilter
# cameraFilterId == 2 => StereoCameraModelFilter
# cameraFilterId == 3 => Raytracing3DBasedSingleCameraModelFilter
# cameraFilterId == 4 => SingleCameraModelFilter
# Note that the first 2 ids are stereo based filters, while the last 2 are based on a single camera.
# Furthermore even ids don't use ray tracing, while odd ids use ray tracing.
cameraFilterId: 1
voxelSize: 0.04
worldHeight: 3
worldFilePath: ./rsc/world/world.xml
# ratingModuleId == 1 => DefaultRatingModule
ratingModuleId: 1
# hypothesisUpdaterId == 1 => PerspectiveHypothesisUpdater
hypothesisUpdaterId: 1
# robotModelId == 1 => MILDRobotModelWithExactIK
# robotModelId == 2 => MILDRobotModelWithApproximatedIK
robotModelId: 1
panMin: -20
panMax: 20
tiltMin: -45
tiltMax: 25
mSigma: 1.0
radius: 0.15 # hexagon space sample radius
sampleSizeUnitSphereSampler: 384 # number of samples created by SpiralApproxUnitSphereSampler. Greater -> more precise orientation.
colThresh: 40 # greater values results in problems during simulation in navigation. Smaller -> more distance to obstacles.
panAngleSamplingStepsPerIteration: 3
inverseKinematicIterationAccuracy: 0.01
enableCropBoxFiltering : false
enableIntermediateObjectWeighting : false
sampleSizeMapBasedRandomSpaceSampler: 100
# spaceSamplerId == 1 => MapBasedHexagonSpaceSampler
# spaceSamplerId == 2 => MapBasedRandomSpaceSampler
# spaceSamplerId == 3 => PlaneSubSpaceSampler
# spaceSamplerId == 4 => Raytracing2DBasedSpaceSampler
spaceSamplerId: 1
# sphereSamplerId == 1 => SpiralApproxUnitSphereSampler
sphereSamplerId: 1
maxIterationSteps: 20
debugLevels: [NONE] # ALL, NONE, PARAMETERS, SERVICE_CALLS, VISUALIZATION, CALCULATION, RATING, ROBOT_MODEL, MAP, WORLD, VOXEL_GRID, FILTER, IK_RATING, SPACE_SAMPLER, HYPOTHESIS_UPDATER
