mOmegaUtility: 840 #Gewichtungsfaktor für den Nutzen-Faktor 
mOmegaPan: 1  #Gewichtungsfaktor für die Bewegung der Pan-Achse der PTU
mOmegaTilt: 1 #Gewichtungsfaktor für die Rotation der Tilt-Achse der PTU
mOmegaRot: 100 #Gewichtungsfaktor für die Rotation der Basis
mOmegaBase: 100 #Gewichtungsfaktor für die Bewegung der Basis
mOmegaRecognizer: 50
speedFactorRecognizer: 2.0 #Zeitkosten für Objekterkennung in Sec/Objekt. Bitte nur nach Ruecksprache mit Pascal ändern.
tolerance: 0.00003 #Toleranzwert für die Wegfindung des globalen Planers
useGlobalPlanner: false
fovx: 30
fovy: 20
ncp: 0.7 #Entfernung der NearClippingPlane in meter
fcp: 1.5 ##Entfernung der FarClippingPlane in meter
show_space_sampling: true
show_point_cloud: true
show_frustum_point_cloud: true
show_frustum_marker_array: true
useNewIK: false
visualizeIK: false
useRaytracing: false #useRaytracing == true => MapBasedStereoCameraModelFilter, useRaytracing == false => StereoCameraModelFilter
move_robot: true
panMin: -20
panMax: 20
tiltMin: -45
tiltMax: 25
mSigma: 0.5
radius: 0.15
sampleSizeUnitSphereSampler: 384
colThresh: 40
panAngleSamplingStepsPerIteration: 20
inverseKinematicIterationAccuracy: 0.005
enableCropBoxFiltering : false
enableIntermediateObjectWeighting : false
sampleSizeMapBasedRandomSpaceSampler: 100
spaceSamplerId: 1 #spaceSamplerId == 1 => MapBasedHexagonSpaceSampler, spaceSamplerId == 2 => MapBasedRandomSpaceSampler
maxIterationSteps: 20
debugLevels: [NONE] #ALL, NONE, PARAMETERS, SERVICE_CALLS, VISUALIZATION, CALCULATION, RATING, ROBOT_MODEL, MAP, FILTER, IK_RATING, SPACE_SAMPLER, HYPOTHESIS_UPDATER
