iterationVisualization: /nbv/iteration_visualization
frustumVisualization: /nbv/frustum_marker_array
objectsVisualization: /nbv/object_meshes
objectNormalsVisualization: /nbv/object_normals
frustumObjectsVisualization: /nbv/frustum_object_meshes
frustumObjectNormalsVisualization: /nbv/frustum_object_normals
cropBoxVisualization: /nbv/crop_box
worldMeshesVisualization: /nbv/worldMeshesVisualization
worldTriangleListVisualization: /nbv/worldTriangleListVisualization
voxelGridVisualization: /nbv/voxelGridVisualization
raytracingVisualization: /nbv/raytracingVisualization
samplingVisualization: /nbv/samplingVisualization