iterationVisualization: /nbv/iteration_visualization
frustumVisualization: /nbv/frustum_marker_array
objectsVisualization: /nbv/object_meshes
objectNormalsVisualization: /nbv/object_normals
frustumObjectsVisualization: /nbv/frustum_object_meshes
cropBoxVisualization: /nbv/crop_box
IKVisualization: /nbv/IK_Visualization
