mOmegaPan: 1.0  #Gewichtungsfaktor für die Bewegung der Pan-Achse der PTU
mOmegaTilt: 10.0 #Gewichtungsfaktor für die Rotation der Tilt-Achse der PTU
mOmegaRot: 1.0 #Gewichtungsfaktor für die Rotation der Basis
mOmegaBase: 3.0 #Gewichtungsfaktor für die Bewegung der Basis
mOmegaUseBase: 8.0 #Zusätzlicher Kostenfaktor der addiert wird, wenn die Basis bewegt wird
speedFactorPTU: 0.05 #Zeitkosten für Drehung der PTU in Sec/Rad
speedFactorBaseRot: 0.1 #Zeitkosten für Drehung der Basis in Sec/Rad
speedFactorBaseMove: 5.0 #Zeitkosten für Bewegung der Basis in Sec/Meter
speedFactorRecognizer: 5.0 #Zeitkosten für Objekterkennung in Sec/Objekt
tolerance: 0.00003 #Toleranzwert für die Wegfindung des globalen Planers
useGlobalPlanner: true
fovx: 31
fovy: 24
ncp: 0.7 #Entfernung der NearClippingPlane in meter
fcp: 1.35 ##Entfernung der FarClippingPlane in meter
show_space_sampling: true
show_point_cloud: true
show_frustum_point_cloud: true
show_frustum_marker_array: true
move_robot: true
recognition_time: 6
panMin: -22
panMax: 19
tiltMin: -50
tiltMax: 20
radius: 0.2
samples: 128
colThresh: 45
