mOmegaPan: 3.0  #Pangeschwindigkeit in Sec/Rad
mOmegaTilt: 3.0 #Tiltgeschwindigkeit in Sec/Rad
mOmegaRot: 3.0 #Rotationsgeschwindigkeit in Sec/Rad
mOmegaBase: 1.0 #Geschwindigkeit der Basis in Sec/Meter
tolerance: 0.00003
useGlobalPlanner: false
fovx: 62.5
fovy: 48.9
ncp: 0.2 #Entfernung der NearClippingPlane in meter
fcp: 10.0 ##Entfernung der FarClippingPlane in meter
show_space_sampling: true
show_point_cloud: true
show_frustum_point_cloud: true
show_frustum_marker_array: true
move_robot: true
recognition_time: 6
panMin: -60
panMax: 60
tiltMin: -45
tiltMax: 45
